### ISSUE TITLE
Motor position and motor behaviour

### ISSUE THREAD

**Issue by psychemedia** [QuirkyCort/ev3dev-sim#13]
From the *About* page in the [demo](https://www.aposteriori.com.sg/Ev3devSim/index.html), I got the impression that the motors stopped immediately. But If I run the following:

```
from ev3dev2.motor import OUTPUT_B, OUTPUT_C
from ev3dev2.motor import MoveTank, SpeedPercent


tank_drive = MoveTank(OUTPUT_B, OUTPUT_C)

def print_wheel_positions():
    print('Left wheel position: {}'.format(tank_drive.left_motor.position))
    print('Right wheel position: {}'.format(tank_drive.right_motor.position))

print_wheel_positions()

left_speed = right_speed = SpeedPercent(20)

for i in range(5):
    tank_drive.on_for_degrees(left_speed, right_speed, 360)
    print("After {} rotation:".format(i))
    print_wheel_positions()
```

I get a report:

```
Left wheel position: 0
Right wheel position: 0
After 0 rotation:
Left wheel position: 385
Right wheel position: 385
After 1 rotation:
Left wheel position: 770
Right wheel position: 770
After 2 rotation:
Left wheel position: 1155
Right wheel position: 1155
After 3 rotation:
Left wheel position: 1540
Right wheel position: 1540
After 4 rotation:
Left wheel position: 1925
Right wheel position: 1925
```

I was expecting the position to report increments of 360 degrees? If I increase the speed, then the `position` count is increased even further at each step?

**Comment by QuirkyCort** [comment]
Bug on my end. The wheel position was still being incremented even when the robot is stopped. I've fixed it.

Note that there will still be a small overrun. This is because the simulator runs in steps, 30 steps per simulated second. So at 20% speed, the wheel will turn approximately 6 to 7 degrees each step. By the time the simulator detects that the wheel has reached 360 degrees, it may have already exceeded it.

I've recently started on https://gears.aposteriori.com.sg/. It's still early work, but you might want to play around with it. All feedback and bug reports are appreciated.

**Comment by psychemedia** [comment]
Hi  - thanks for that; I'm still getting up to speed (doh!) with the simulator code.

The new simulator looks interesting, but I'm heavily invested in some teaching materials developed around a fork of this repo that wraps the simulator in an `ipywidget` for use in Jupyter notebooks: [`nbev3devsim`](https://github.com/innovationOUtside/nbev3devsim/) (teaching materials under development [here](https://github.com/innovationOUtside/tm129-robotics2020/blob/master/seminar_tm129_robotics_overview.md)). (I've tried to keep the code where it could perhaps be contributed back, but my dev skills are limited and I'm focussed more on just hacking something I can use for teaching...)

It should be possible to pull everything back out of the Jupyter notebook context and eg into a notebook style HTML page, just relying on the Skulpt python, but that's on the "nice to have" when I finish my notebook based work.

**Comment by psychemedia** [comment]
re: "By the time the simulator detects that the wheel has reached 360 degrees, it may have already exceeded it." I guess in teaching I could make a feature out of that and classify it as as "computational momentum" error!

**Comment by QuirkyCort** [comment]
Wow. It's great to know that the simulator is useful to your course.

I'll still be maintaining the 2D simulator for the foreseeable future. Major new features are unlikely as I put greater focus on the new 3D simulator, but don't let that stop you from suggesting.

**Comment by psychemedia** [comment]
@QuirkyCort I've got various attempts at certain things (basic sensor and motor noise, a view of what the light sensors see, pen down, canvas drag) but the code is a but clunky. If it's useful, when I get a chance, I'll try to identify bits of that implement particular features (my commit history is all over the place and not overly useful as I "work towards" solutions through various levels of brokenness!) and then either make a PR or start a thread as a discussion item with possible implementation.
